- name: Download and run installer
  shell:
    cmd: "curl -sfL https://get.rke2.io | sh -"

- name: Enable rke2-server service 
  ansible.builtin.systemd:
    name: rke2-server.service
    enabled: true

- name: Start rke2-server service 
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started

- name: Save kubeconfig in local ~/.kube/
  ansible.builtin.fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ~/.kube/config
    flat: true

- name: Get token for joining agent
  ansible.builtin.fetch:
    src: /var/lib/rancher/rke2/server/node-token
    dest: /tmp/
    flat: true