- name: Download and run installer in agent mode
  ansible.builtin.shell:
    cmd: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -

- name: Enable rke2-server service 
  ansible.builtin.systemd:
    name: rke2-server.service
    enabled: true

- name: Create directory for config file
  ansible.builtin.shell:
    cmd: mkdir -p /etc/rancher/rke2/

- name: Create config file for connecting to server
  ansible.builtin.shell:
    cmd: "echo server: https://{{ server_ip }}:9345\ntoken: {{ }} >> /etc/rancher/rke2/config.yaml"

- name: Start rke2-server service 
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started