- name: Download and run installer in agent mode
  shell:
    cmd: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -

- name: Enable rke2-server service 
  ansible.builtin.systemd:
    name: rke2-server.service
    enabled: true

- name: Create directory for config file
  shell:
    cmd: mkdir -p /etc/rancher/rke2/

- name: Upload config file for connecting to server
  template:
    src: config.yaml
    dest: /etc/rancher/rke2/config.yaml

- name: Start rke2-server service 
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started