
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m
  releaseName: longhorn
  targetNamespace: longhorn
  chart:
    spec:
      chart: flux/charts/longhorn
      sourceRef:
        kind: GitRepository
        name: charts
  values: