apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: clusty-dusty
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/Salazar-99/clusty-dusty
  secretRef:
    name: flux-system
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/flux/charts/