- name: Download and install Flux
  shell:
    cmd: curl -s https://fluxcd.io/install.sh | sudo bash

- name: Run Flux bootstrap
  shell:
    cmd: >
      flux bootstrap github
      --owner=Salazar-99
      --repository=clusty-dusty
      --branch=main
      --path=flux/flux-system/
      --personal