
---
- name: Prepare all nodes
  hosts: optiplex
  become: true
  gather_facts: true
  roles:
  - role: k8s-node

# - name: Install RKE on servers
#   hosts: servers
#   become: true
#   roles:
#   - role: server

# - name: Install RKE on agents and join them to the cluster
#   hosts: agents
#   roles:
#   - role: agent


