---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 3m
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: flux/charts/cert-manager
      sourceRef:
        kind: GitRepository
        name: clusty-dusty-charts
  values:
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: VmxazY2v7HaIu_VZrvri3DBmUbOKjW-QiOQ7m6HX
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: gfsalazar01@gmail.com
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: tls-private-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token