---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 3m
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: flux/charts/cert-manager
      sourceRef:
        kind: GitRepository
        name: clusty-dusty-charts
  values: