apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: clusty-dusty-charts
  namespace: flux-system
spec:
  interval: 3m0s
  secretRef:
    name: flux-system
  url: ssh://git@github.com/Salazar-99/clusty-dusty
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/flux/charts/