apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 3m
  releaseName: metallb
  targetNamespace: metallb
  chart:
    spec:
      chart: flux/charts/metallb
      sourceRef:
        kind: GitRepository
        name: clusty-dusty-charts
  values: